version: 2

build:
    os: ubuntu-22.04
    apt_packages:
        - libcurl4-openssl-dev
    tools:
        python: "3"

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true

python:
     install:
         - method: pip
           path: .
           extra_requirements:
               - doc
