name: test-env

channels:
    - conda-forge
    - defaults

dependencies:
    # runtime dependencies
    - python>=3.8
    - pycurl>=7.44.0
    - tenacity>=6.2.0
    - tqdm>=4.50.0
    # testing dependencies
    - black
    - mypy>=0.981
    - pytest
    - pytest-cov
    - pytest-httpserver
    - pytest-mock
    - pytest-mypy
    - pytest-pylint
    - pylint
    - pytest-sugar>=0.9.7
    - setuptools-scm[toml]
    - types-pycurl
    - types-tqdm
    # editable install and testing dependencies missing from conda-forge
    - pip
    - pip:
        - pytest-black-ng
        - pytest-isort
        - -e ../..
