name: test-env

channels:
    - conda-forge
    - defaults

dependencies:
    # runtime dependencies
    - python>=3.8
    - main::pycurl>=7.44.0
    - tenacity>=6.2.0
    - tqdm>=4.50.0
    # testing dependencies
    - black
    - pytest
    - pytest-cov
    - pytest-httpserver
    - pytest-mock
    - pytest-mypy
    - pylint
    - pytest-sugar
    - setuptools-scm[toml]
    - types-pycurl
    - types-tqdm
    - attrs
    # editable install and unsatisfied runtime dependencies
    - pip
    - pip:
        - pytest-black-ng
        - pytest-isort
        - pytest-pylint
        - -e ../..
