name: Tests with Coverage and Static Analysis

on:
    pull_request:
    push:
        branches:
            - master
            - develop
            - 'release/**'
            - 'workflow/**'

jobs:
    test-linux-venv:
        strategy:
            matrix:
                python-version: ['3.11', '3.10', '3.9', '3.8', 'pypy3.9', 'pypy3.8']

        name: Test Linux / Python ${{ matrix.python-version }} / venv
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install required Ubuntu packages
              run: |
                  sudo -n apt-get update -y
                  sudo -n apt-get install -y --no-upgrade libcurl4-openssl-dev

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package in editable mode and its dependencies
              run: ./venv.sh install-venv

            - name: Disable static analysis coverage on PyPy
              if: ${{ startsWith(matrix.python-version, 'pypy') }}
              run: sed -i '/^addopts\>/s/^/#/' pyproject.toml

            - name: Tests with code coverage and pylint, mypy static analysis
              run: ./venv.sh pytest

            - name: Security issues static analysis
              run: ./venv.sh bandit -c pyproject.toml -r .

    test-platform-packages:
        strategy:
            matrix:
                platform-image: [ubuntu-latest, ubuntu-20.04]

        name: Test Linux / ${{ matrix.platform-image }} / platform
        runs-on: ${{ matrix.platform-image }}

        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install maximal subset of platform Python packages
              run: |
                  sudo -n apt-get update -y
                  sudo -n apt-get install -y python3-{pycurl,tenacity,tqdm}
                  sudo -n apt-get install -y python3-{bandit,filelock,mypy,pytest,toml,werkzeug,wheel}
                  sudo -n apt-get install -y python3-pytest-{cov,pylint,sugar,xdist}
                  sudo -n apt-get install -y python3-pytest-repeat || :

            - name: Install package and its platform-unavailable dependencies
              run: |
                  pip3 install --user -U pip
                  pip3 install --user --use-pep517 '.[test]'
                  find src -mindepth 1 -delete

            - name: Tests with essentially no static analysis
              run: pytest-3 --no-cov

    test-dependency-sanity:
        name: Test Sanity on Linux / platform
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install minimal subset of platform Python packages
              run: |
                  sudo -n apt-get update -y
                  sudo -n apt-get install -y python3-{pycurl,tenacity,tqdm}

            - name: Install package and clean out repository files
              run: |
                  pip3 install --user -U pip
                  pip3 install --user --use-pep517 --no-deps .
                  find . -mindepth 1 -delete

            - name: Sanity tests for package availability
              run: |
                  curldl -h
                  curldl -V
                  curldl -vpo test.html https://github.com/
